site:
  name: แป้นพิมพ์มนูญชัย
  site: 'https://manoonchai.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: no

# Default SEO metadata
metadata:
  title:
    default: แป้นพิมพ์มนูญชัย
    template: '%s — แป้นพิมพ์มนูญชัย'
  description: "แป้นพิมพ์ภาษาไทยทางเลือกใหม่ สร้างจากปัญญาประดิษฐ์และฐานข้อมูลขนาดใหญ่ของการพิมพ์ภาษาไทยในยุคปัจจุบัน พิมพ์ง่ายกว่าแป้นพิมพ์เกษมณีถึง 45%"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: แป้นพิมพ์มนูญชัย
    images:
      - url: '~/assets/images/manoonchai-layout.png'
        width: 1747
        height: 617
    type: website
  twitter:
    handle: '@narze'
    site: '@narze'
    cardType: summary_large_image

i18n:
  language: th
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
